import { pgTable, text, boolean, timestamp, integer, jsonb, uuid, pgEnum } from 'drizzle-orm/pg-core';

export const jobStatusEnum = pgEnum('job_status', ['pending', 'running', 'completed', 'failed']);

export const scrapeJobs = pgTable('scrape_jobs', {
  id: uuid('id').primaryKey().defaultRandom(),
  userId: text('user_id').notNull(),
  url: text('url').notNull(),
  status: jobStatusEnum('status').default('pending').notNull(),
  options: jsonb('options').default({}),
  startedAt: timestamp('started_at'),
  completedAt: timestamp('completed_at'),
  pagesScraped: integer('pages_scraped').default(0),
  totalLinksFound: integer('total_links_found').default(0),
  errorMessage: text('error_message'),
  aiPrompt: text('ai_prompt'),
  aiExtractionData: jsonb('ai_extraction_data'),
  antiBot: boolean('anti_bot').default(false),
  embeddings: jsonb('embeddings').default([]),
  createdAt: timestamp('created_at').defaultNow().notNull(),
});

export const monitors = pgTable('monitors', {
  id: uuid('id').primaryKey().defaultRandom(),
  userId: text('user_id').notNull(),
  url: text('url').notNull(),
  label: text('label'),
  intervalMinutes: integer('interval_minutes').default(60).notNull(),
  isActive: boolean('is_active').default(true).notNull(),
  lastCheckedAt: timestamp('last_checked_at'),
  lastChangedAt: timestamp('last_changed_at'),
  lastContentHash: text('last_content_hash'),
  lastSnapshotText: text('last_snapshot_text'),
  changeCount: integer('change_count').default(0),
  lastDiff: jsonb('last_diff').default({}),
  createdAt: timestamp('created_at').defaultNow().notNull(),
});

export const scrapeResults = pgTable('scrape_results', {
  id: uuid('id').primaryKey().defaultRandom(),
  jobId: uuid('job_id').references(() => scrapeJobs.id, { onDelete: 'cascade' }).notNull(),
  pageUrl: text('page_url').notNull(),
  title: text('title'),
  metaDescription: text('meta_description'),
  headings: jsonb('headings').default({}),
  paragraphs: jsonb('paragraphs').default([]),
  linksInternal: jsonb('links_internal').default([]),
  linksExternal: jsonb('links_external').default([]),
  images: jsonb('images').default([]),
  emails: jsonb('emails').default([]),
  phones: jsonb('phones').default([]),
  socialLinks: jsonb('social_links').default([]),
  metadata: jsonb('metadata').default({}),
  techStack: jsonb('tech_stack').default({}),
  tablesData: jsonb('tables_data').default([]),
  formsData: jsonb('forms_data').default([]),
  wordCount: integer('word_count').default(0),
  loadTimeMs: integer('load_time_ms').default(0),
  // ─── Advanced extraction fields ───
  scripts: jsonb('scripts').default([]),
  stylesheets: jsonb('stylesheets').default([]),
  comments: jsonb('comments').default([]),
  leakedData: jsonb('leaked_data').default({}),
  securityInfo: jsonb('security_info').default({}),
  hiddenFields: jsonb('hidden_fields').default([]),
  iframes: jsonb('iframes').default([]),
  downloads: jsonb('downloads').default([]),
  videos: jsonb('videos').default([]),
  suggestions: jsonb('suggestions').default([]),
  contactInfo: jsonb('contact_info').default({}),
  seoScore: jsonb('seo_score').default({}),
  // ─── NEW: Performance & Quality Metrics ───
  performanceMetrics: jsonb('performance_metrics').default({}),
  accessibilityScore: jsonb('accessibility_score').default({}),
  contentQuality: jsonb('content_quality').default({}),
  // ─── ELITE: Deep extraction fields ───
  rssFeeds: jsonb('rss_feeds').default([]),
  apiEndpoints: jsonb('api_endpoints').default([]),
  colorPalette: jsonb('color_palette').default({}),
  fontInfo: jsonb('font_info').default({}),
  pricing: jsonb('pricing').default([]),
  reviews: jsonb('reviews').default([]),
  faqs: jsonb('faqs').default([]),
  breadcrumbs: jsonb('breadcrumbs').default([]),
  navigation: jsonb('navigation').default({}),
  openAPIs: jsonb('open_apis').default([]),
  pageFingerprint: jsonb('page_fingerprint').default({}),
  languageInfo: jsonb('language_info').default({}),
  copyright: jsonb('copyright').default({}),
  schemaOrg: jsonb('schema_org').default({}),
  microdata: jsonb('microdata').default([]),
  linkRelations: jsonb('link_relations').default([]),
  responseHeaders: jsonb('response_headers').default({}),
  // ─── ELITE: Site-wide intelligence ───
  siteIntel: jsonb('site_intel').default({}),
  // ─── BRUTAL: Deep reconnaissance & intelligence ───
  brutalRecon: jsonb('brutal_recon').default({}),
  browserIntel: jsonb('browser_intel').default({}),
  contentIntel: jsonb('content_intel').default({}),
  securityAudit: jsonb('security_audit').default({}),
  cmsInfo: jsonb('cms_info').default({}),
  rawText: text('raw_text'),
  scrapedAt: timestamp('scraped_at').defaultNow().notNull(),
});


